### ISSUE TITLE
Support for TypeScript with Feathers 4

### ISSUE THREAD

**Issue by alinex** [feathersjs-ecosystem/feathers-logger#30]
I want to include your package in a new Feathers 4 app using typescript but could not get it done.

I made the following middleware but had to ignore a typescript error because definitions are missing.

```ts
import winston from 'winston';
// @ts-ignore
import logger from 'feathers-logger';
import { Application } from '../declarations';

export default function(app: Application) {
    app.configure(logger(winston));
}
```

But also every time I use app.debug() or any of the other methods I also has to ignore these lines in TS. 

How to get it done correctly?

**Comment by daffl** [comment]
A PR would be accepted but I don't have plans adding them myself. This is a 30 lines of code module that is not used in a generated application where you can just require the logger from the `logger` file directly or easily add it to `app` if you prefer to access it from there. I'm inclined to archive this module because it doesn't really do anything useful.

**Comment by daffl** [comment]
This module has now been archived. https://github.com/feathersjs-ecosystem/feathers-logger#migrating mentions how to access the Winston logger that is already included in a normal application.
